### ISSUE TITLE
消息发送不出来，用其他插件的转发又可以发出来

### ISSUE THREAD

**Issue by yunwei97** [MSIsunny/GenshinWishCalculator-plugin#1]
ApiRejection { code: -70, message: '群消息发送失败，可能被风控' }

**Comment by MSIsunny** [comment]
或许重启一下云崽就能发送出来？如果仍然不行请告诉我。

**Comment by yunwei97** [comment]
> 

 重启了还是不行 应该是我机器人QQ的问题吧 我把你的文字转成图片再发送就可以了

**Comment by MSIsunny** [comment]
OK，不影响功能使用的话暂时就这样吧
